feat: complete workflow

diff --git a/.github/workflows/terraform.speculative-run.workflow.yml b/.github/workflows/terraform.speculative-run.workflow.yml
--- a/.github/workflows/terraform.speculative-run.workflow.yml
+++ b/.github/workflows/terraform.speculative-run.workflow.yml
@@ -7,7 +7,15 @@ on:
     branches:
       - main
 
+env:
+  TF_CLOUD_ORGANIZATION: "${{ vars.TF_CLOUD_ORGANIZATION }}" ## Name of your existing HCP Terraform Organization. RECOMMENDED: use repository variables. ex. "${{ vars.TF_CLOUD_ORGANIZATION }}"
+  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}" ## HCP Terraform API Token. RECOMMENDED: replace with github action secrets. ex. "${{ secrets.TF_API_TOKEN }}"
+  TF_WORKSPACE: "${{ vars.TF_WORKSPACE }}" ## Name of your existing workspace in HCP Terraform.
+  CONFIG_DIRECTORY: "./" ## Directory of your Terraform Configuration. Relative to the project root.
+
+
 jobs:
+  ## NOTE: Represents a job that does not need approval and does not have a declared dependency for a deployment.
   build:
     runs-on: ubuntu-latest
     steps:
@@ -17,14 +25,85 @@ jobs:
       - name: Run Tests
         run: echo "Running tests..."
 
+  ## NOTE: Represents the approval required job, that can't proceed until selected members approve it. 
   deploy:
     needs: build
     runs-on: ubuntu-latest
     environment:
-      name: dev  # Dynamic environment name based on branch name
-      # url: https://example.com/${{ github.head_ref }} # Optional URL for the environment
+      # Deployment can be a staticly created environment or a dynamically created one.
+      # If dynamically created, would need to script assigning the appropriate approvers with the GitHub API and GITHUB_TOKEN env variable.
+      name: dev       
+      ## NOTE: optional `url: https://example.com/${{ github.head_ref }}` # Optional URL for the environment
     steps:
-      - name: Wait for Approval
-        run: echo "Awaiting approval for deployment to environment ${{ github.head_ref }}-env..."
-      - name: Deploy to Environment
-        run: echo "Deploying to ${{ github.head_ref }}-env..."
+      - uses: actions/checkout@v3
+
+      - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
+        id: upload
+        with:
+          workspace: ${{ env.TF_WORKSPACE }}
+          directory: ${{ env.CONFIG_DIRECTORY }}
+          speculative: true
+
+      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
+        id: run
+        ## run may fail, if so continue to output PR comment
+        ## step.terraform-cloud-check-run-status will fail job after pr comment is created/updated.
+        continue-on-error: true
+        with:
+          workspace: ${{ env.TF_WORKSPACE }}
+          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
+          plan_only: true
+          ## OPTIONAL: set your own message for run. A default message will be defined for you.
+          ## Example:
+          # message: "Triggered From GitHub Actions CI ${{ github.sha }}"
+
+      - uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.3.2
+        id: plan-output
+        with:
+          plan: ${{ steps.run.outputs.plan_id }}
+      
+      - uses: actions/github-script@v6
+        if: github.event_name == 'pull_request'
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            // 1. Retrieve existing bot comments for the PR
+            const { data: comments } = await github.rest.issues.listComments({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number,
+            })
+            const botComment = comments.find(comment => {
+              return comment.user.type === 'Bot' && comment.body.includes('HCP Terraform Plan Output')
+            })
+            const output = `#### HCP Terraform Plan Output
+               \`\`\`\n
+               Plan: ${{ steps.plan-output.outputs.add }} to add, ${{ steps.plan-output.outputs.change }} to change, ${{ steps.plan-output.outputs.destroy }} to destroy.
+               \`\`\`
+               [HCP Terraform Plan](${{ steps.run.outputs.run_link }})
+               `
+            // 3. If we have a comment, update it, otherwise create a new one
+            if (botComment) {
+              github.rest.issues.updateComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                comment_id: botComment.id,
+                body: output
+              })
+            } else {
+              github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: output
+              })
+            }
+
+        ## Check Run Status, if not planned_and_finished fail the job
+      - id: terraform-cloud-check-run-status
+        if: ${{ steps.run.outputs.run_status != 'planned_and_finished'}}
+        run: |
+          echo "HCP Terraform Run Failed or Requires Further Attention"
+          echo "Run Status: '${{ steps.run.outputs.run_status }}'"
+          echo "${{ steps.run.outputs.run_link }}"
+          exit 1
